src/Entity/Band.php
<?php

namespace App\Entity;

use App\Repository\BandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BandRepository::class)
 */
class Band
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Style;

    /**
     * @ORM\ManyToOne(targetEntity=Picture::class, inversedBy="bands")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Picture;

    /**
     * @ORM\Column(type="date")
     */
    private $YearOfCreation;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $LastAlbumName;

    /**
     * @ORM\ManyToMany(targetEntity=ShowList::class, mappedBy="Band")
     */
    private $shows;

    /**
     * @ORM\OneToMany(targetEntity=Member::class, mappedBy="Band")
     */
    private $members;

    public function __construct()
    {
        $this->shows = new ArrayCollection();
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getStyle(): ?string
    {
        return $this->Style;
    }

    public function setStyle(string $Style): self
    {
        $this->Style = $Style;

        return $this;
    }

    public function getPicture(): ?Picture
    {
        return $this->Picture;
    }

    public function setPicture(?Picture $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getYearOfCreation(): ?\DateTimeInterface
    {
        return $this->YearOfCreation;
    }

    public function setYearOfCreation(\DateTimeInterface $YearOfCreation): self
    {
        $this->YearOfCreation = $YearOfCreation;

        return $this;
    }

    public function getLastAlbumName(): ?string
    {
        return $this->LastAlbumName;
    }

    public function setLastAlbumName(string $LastAlbumName): self
    {
        $this->LastAlbumName = $LastAlbumName;

        return $this;
    }

    /**
     * @return Collection|ShowList[]
     */
    public function getShows(): Collection
    {
        return $this->shows;
    }

    public function addShow(ShowList $show): self
    {
        if (!$this->shows->contains($show)) {
            $this->shows[] = $show;
            $show->addBand($this);
        }

        return $this;
    }

    public function removeShow(ShowList $show): self
    {
        if ($this->shows->removeElement($show)) {
            $show->removeBand($this);
        }

        return $this;
    }

    /**
     * @return Collection|Member[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Member $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setBand($this);
        }

        return $this;
    }

    public function removeMember(Member $member): self
    {
        if ($this->members->removeElement($member)) {
            // set the owning side to null (unless already changed)
            if ($member->getBand() === $this) {
                $member->setBand(null);
            }
        }

        return $this;
    }
}

src/Entity/ShowList.php
<?php

namespace App\Entity;

use App\Repository\ShowListRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ShowListRepository::class)
 * @ORM\Table(name="`showlist`")
 */
class ShowList
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=Band::class, inversedBy="shows")
     */
    private $Band;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $TourName;

    /**
     * @ORM\ManyToOne(targetEntity=Hall::class, inversedBy="shows")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Hall;

    public function __construct()
    {
        $this->Band = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Band[]
     */
    public function getBand(): Collection
    {
        return $this->Band;
    }

    public function addBand(Band $band): self
    {
        if (!$this->Band->contains($band)) {
            $this->Band[] = $band;
        }

        return $this;
    }

    public function removeBand(Band $band): self
    {
        $this->Band->removeElement($band);

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTourName(): ?string
    {
        return $this->TourName;
    }

    public function setTourName(?string $TourName): self
    {
        $this->TourName = $TourName;

        return $this;
    }

    public function getHall(): ?Hall
    {
        return $this->Hall;
    }

    public function setHall(?Hall $Hall): self
    {
        $this->Hall = $Hall;

        return $this;
    }
}

src/Controller/ConcertController.php
<?php

namespace App\Controller;

use App\Entity\Band;
use App\Entity\Member;
use App\Entity\ShowList;
use App\Entity\User;
use App\Form\BandType;
use App\Form\MemberType;
use App\Form\ShowListType;
use App\Form\UserType;
use Symfony\Component\HttpFoundation\Request;;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class ConcertController extends AbstractController
{
    /**
     * Affichage de la liste des concerts à venir
     *
     * @Route("/", name="concert")
     */
    public function index(): Response
    {
        $repository = $this->getDoctrine()->getRepository(ShowList::class);
        return $this->render('concert/index.html.twig', [
                'concerts' => $repository->findAll()
            ]
        );
    }

    /**
     * Affiche une liste de tous les concerts
     *
     * @Route("/concert", name="list")
     */
    public function list(): Response
    {
        $repository = $this->getDoctrine()->getRepository(ShowList::class);
        return $this->render('concert/concert.html.twig', [
                'name' => "list",
                'concerts' => $repository->findAll()
            ]
        );
    }

    /**
     * Affiche une liste de groupes
     *
     * @return Response
     *
     * @Route("/group", name="group")
     */
    public function group(): Response
    {
        $repository = $this->getDoctrine()->getRepository(Band::class);
        return $this->render('concert/group.html.twig', [
                'groups' => $repository->findAll()
            ]
        );
    }


    /**
     * Créer un nouveau groupe
     *
     * @Route("/group/create", name="groupe_create")
     * @param Request $request
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */
    public function createGroupe(Request $request): Response
    {
        $groupe = new Band();

        $form = $this->createForm(BandType::class, $groupe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getDate() holds the submitted values
            // but, the original `$task` varibale has also been updated
            $groupe = $form->getData();

            // ... perform some action, such as saving the task to the database
            // for example, if task is a doctrine entity, save it !
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($groupe);
            $entityManager->flush();
            return $this->redirectToRoute('concert');
        }
        return $this->render('concert/newGroupe.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Update un groupe
     *
     * @Route("/group/edit/{id}", name="groupe_edit")
     * @param Request $request
     * @param Band $groupe
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */

    public function editGroupe(Request $request, Band $groupe): Response
    {
        $form = $this->createForm(BandType::class, $groupe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $groupe = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($groupe);
            $entityManager->flush();

            $this->addFlash('success', 'Concert update! Music is power!');
            return $this->redirectToRoute('list');
        }

        return $this->render('concert/newGroupe.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Affiche le detail d'un groupe
     *
     * @param Band $groupe
     * @return Response
     *
     * @Route("/group/{id}", name="group_detail")
     */
    public function group_detail(Band $groupe): Response
    {
        return $this->render('concert/detail.html.twig', [
                'groups' => $groupe
            ]
        );
    }

    /**
     * Créer un nouveau membre
     *
     * @Route("group/membre/create", name="groupe_create")
     * @param Request $request
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */
    public function createMembre(Request $request): Response
    {
        $membre = new Member();

        $form = $this->createForm(MemberType::class, $membre);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getDate() holds the submitted values
            // but, the original `$task` varibale has also been updated
            $membre = $form->getData();

            // ... perform some action, such as saving the task to the database
            // for example, if task is a doctrine entity, save it !
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($membre);
            $entityManager->flush();
            return $this->redirectToRoute('concert');
        }
        return $this->render('concert/newMembre.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Update un membre
     *
     * @Route("/group/membre/edit/{id}", name="membre_edit")
     * @param Request $request
     * @param Member $membre
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */

    public function editMembre(Request $request, Member $membre): Response
    {
        $form = $this->createForm(MemberType::class, $membre);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $membre = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($membre);
            $entityManager->flush();

            $this->addFlash('success', 'Membre update');
            return $this->redirectToRoute('group');
        }

        return $this->render('concert/newMembre.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Supprime un membre
     *
     * @Route("/group/membre/delete/{id}", name="delete_membre")
     * @isGranted("ROLE_ADMIN")
     * @param Request $request
     * @param Member $membre
     * @return Response
     */
    public function deleteMembre(Request $request, Member $membre): Response
    {
        if (!$membre) {
            throw $this->createNotFoundException('No membre found');
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($membre);
        $em->flush();
        return $this->redirectToRoute('concert');
    }

    /**
     * Supprime un groupe
     *
     * @Route("/group/delete/{id}", name="delete_groupe")
     * @isGranted("ROLE_ADMIN")
     * @param Request $request
     * @param Band $band
     * @return Response
     */
    public function deleteGroupe(Request $request, Band $band): Response
    {
        if (!$band) {
            throw $this->createNotFoundException('No group found');
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($band);
        $em->flush();
        return $this->redirectToRoute('concert');
    }

    /**
     * Créer un nouveau concert
     *
     * @Route("/concert/create", name="concert_create")
     * @param Request $request
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */
    public function createConcert(Request $request): Response
    {
        $show = new ShowList();

        $form = $this->createForm(ShowListType::class, $show);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getDate() holds the submitted values
            // but, the original `$task` varibale has also been updated
            $show = $form->getData();

            // ... perform some action, such as saving the task to the database
            // for example, if task is a doctrine entity, save it !
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($show);
            $entityManager->flush();
            return $this->redirectToRoute('concert');
        }
        return $this->render('concert/new.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Update un concert
     *
     * @Route("/concert/edit/{id}", name="concert_edit")
     * @param Request $request
     * @param ShowList $concert
     * @isGranted("ROLE_ADMIN")
     * @return Response
     */

    public function editConcert(Request $request, ShowList $concert): Response
    {
        $form = $this->createForm(ShowListType::class, $concert);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $concert = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($concert);
            $entityManager->flush();

            $this->addFlash('success', 'Concert update! Music is power!');
            return $this->redirectToRoute('list');
        }

        return $this->render('concert/new.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * Affiche le detail d'un concert
     *
     * @Route("/concert/{id}", name="concert_detail")
     * @param ShowList $concert
     * @return Response
     * @isGranted("ROLE_ADMIN")
     *
     */
    public function concertDetail(ShowList $concert): Response
    {
        return $this->render('concert/detailConcert.html.twig', [
                'concert' => $concert
            ]
        );
    }

    /**
     * Supprime un concert
     *
     * @Route("/concert/delete/{id}", name="delete_concert")
     * @isGranted("ROLE_ADMIN")
     */
    public function deleteConcert(Request $request, ShowList $concert): Response
    {
        if (!$concert) {
            throw $this->createNotFoundException('No concert found');

templates/concert/concert.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page_liste">
        <h1>Tous nos concerts !</h1>
        <div class="container show_room">
                {% for concert in concerts %}
                    <div class="cards">
                        <h3>{{ concert.tourName }}</h3>
                        <ul>
                            <li>{{ concert.date|date("d/m/Y") }}</li>
                            <li>{{ concert.hall.name }}</li>
                        </ul>
                        <p class="desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut debitis ea est non saepe! Accusantium eaque earum eveniet exercitationem facere, fugiat hic, laborum, quas quasi quibusdam repellat reprehenderit voluptates! Aut dolores dolorum modi, nam neque nostrum odit optio quasi sequi?</p>
                        <a href="{{ path("list") }}/{{ concert.getId() }}">Détails</a>
                    </div>
                {% endfor %}
        </div>
        <div class="create">
            <a href="{{ path('concert_create') }}" class="newConcert">Créer un nouveau concert !</a>
        </div>
    </div>
{% endblock %}

templates/concert/detail.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page_liste">
            <div class="container show_room">
                {% for membre in groups.getMembers() %}
                    <div class="cards">
                        <img src="{{ asset(membre.getPicture().getUrl()) }}" alt="" class="img_membre">
                        <h3>{{ membre.getName() }} {{ membre.getFirstName() }}</h3>
                        <ul id="desc">
                            <li class="year">Date de naissance : {{ membre.getBirthDate|date("d/m/Y") }}</li>
                            <li class="Job">Rôle : {{ membre.getJob() }}</li>
                            <li class="band">Groupe : {{ groups.getName() }}</li>
                        </ul>
                        <a href="{{ path('group') }}/membre/edit/{{ membre.id }}">Modifier le membre</a>
                        <a href="{{ path('group') }}/membre/delete/{{ membre.id }}">Supprimer le membre</a>
                    </div>
                {% endfor %}
            </div>
        <h2>Concerts à venir !</h2>
        <div class="container show_room">
            {% for show in groups.shows %}
                <div class="cards">
                    <h3>{{ show.tourName }}</h3>
                    <ul>
                        <li>{{ show.date|date("d/m/Y") }}</li>
                        <li>{{ show.hall.name }}</li>
                    </ul>
                    <p class="desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut debitis ea est non saepe! Accusantium eaque earum eveniet exercitationem facere, fugiat hic, laborum, quas quasi quibusdam repellat reprehenderit voluptates! Aut dolores dolorum modi, nam neque nostrum odit optio quasi sequi?</p>
                    <a href="{{ path("list") }}/{{ show.getId() }}">Détails</a>
                </div>
            {% endfor %}
        </div>
        <div class="edit"><a href="{{ path('group') }}/edit/{{ groups.id }}">Modifier le groupe</a></div>
        <div class="delete"><a href="{{ path('group') }}/delete/{{ groups.id }}">Supprimer le groupe</a></div>
    </div>
{% endblock %}

templates/concert/detailConcert.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page_liste">
            <div class="container show_room">
                <div class="cards">
                    <h3>{{ concert.tourName }}</h3>
                    <ul>
                        <li>{{ concert.date|date("d/m/Y") }}</li>
                        <li>{{ concert.hall.name }}</li>
                    </ul>
                    <p class="desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut debitis ea est non saepe! Accusantium eaque earum eveniet exercitationem facere, fugiat hic, laborum, quas quasi quibusdam repellat reprehenderit voluptates! Aut dolores dolorum modi, nam neque nostrum odit optio quasi sequi?</p>
                    <a href="{{ path("list") }}/edit/{{ concert.id }}">Modifier le concert</a>
                    <a href="{{ path("list") }}/delete/{{ concert.id }}">Supprimer le concert</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/concert/group.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page_liste">
        <h2>Liste des groupes</h2>
            <div class="container show_room">
                {% for group in groups %}
                    <div class="cards">
                        <img src="{{ asset(group.getPicture().getUrl()) }}" alt="" class="img_grp">
                        <h3>{{ group.getName() }}</h3>
                        <ul id="desc">
                            <li class="year">Année de création : <span class="details">{{ group.getYearOfCreation|date("Y") }}</span></li>
                            <li class="style">Style musical : <span class="details">{{ group.getStyle() }}</span></li>
                            <li class="lastAlbum">Dernier Album : <span class="details">{{ group.getLastAlbumName() }}</span></li>
                            <li class="link"><a href="{{ path("group") }}/{{ group.getId() }}">Détails</a></li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        <div class="create"><a href="{{ path("groupe_create") }}">Créer un nouveau groupe !</a></div>
        </div>
    </div>
{% endblock %}

templates/concert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ConcertController!{% endblock %}

{% block body %}
    <div class="page_liste">
        <h1>Concert à venir !</h1>
        <div class="container show_room">
            {% for concert in concerts %}
                {% if date() < concert.date %}
                    <div class="cards">
                        <h3>{{ concert.tourName }}</h3>
                        <ul>
                            <li>{{ concert.date|date("d/m/Y") }}</li>
                            <li>{{ concert.hall.name }}</li>
                        </ul>
                        <p class="desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut debitis ea est non saepe! Accusantium eaque earum eveniet exercitationem facere, fugiat hic, laborum, quas quasi quibusdam repellat reprehenderit voluptates! Aut dolores dolorum modi, nam neque nostrum odit optio quasi sequi?</p>
                        <a href="{{ path("list") }}/{{ concert.id }}">Détails</a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="create">
            <a href="{{ path('concert_create') }}" class="newConcert">Créer un nouveau concert !</a>
        </div>
    </div>
{% endblock %}

templates/concert/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page_liste">
            <div class="container show_room">
                {% for concert in concerts %}
                    <div class="cards">
                        <img src="{{ asset("images/concert2.jpg") }}" alt="" class="img_grp">
                        <h3>{{ concert }}</h3>
                        <p class="desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut debitis ea est non saepe! Accusantium eaque earum eveniet exercitationem facere, fugiat hic, laborum, quas quasi quibusdam repellat reprehenderit voluptates! Aut dolores dolorum modi, nam neque nostrum odit optio quasi sequi?</p>
                        <a href="{{ path("concert_detail") }}/{{ concert.getId() }}">Détails</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/concert/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Création d'un concert</h1>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <button id="send" type="submit">Save</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/concert/newGroupe.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block title %}Inscrivez-vous !{% endblock %}
{% block body %}
    <div class="container form">
        <h1>Création un nouveau groupe !</h1>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <button id="send" type="submit">Envoyer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/concert/newMembre.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block title %}Inscrivez-vous !{% endblock %}
{% block body %}
    <div class="container form">
        <h1>Création un nouveau groupe !</h1>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <button id="send" type="submit">Envoyer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}